---
- name: apache-setup
  hosts: dev
  become: true
  gather_facts: false
  tasks:
    - name: Copy content to httpd file
      ansible.builtin.copy:
        src: alias.conf
        dest: /etc/httpd/conf
      notify: restart apache

  handlers:
    - name: restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted

#Example Run:
#ansible-navigator run apache-setup.yml --eei ee-supported-rhel8:latest -pp missing -m stdout
