---
- name: create remote users
  hosts: all
  become: yes
  vars_files:
    - users_list.yml
  vars:
    password: "{{ lookup('password', 'filename-' + item.name + 'length=6 chars=digits') }}"
  tasks:
    - name: create users
      user:
        name: "{{ item.name}}"
        uid: "{{ item.uid }}"
        state: present
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create
        comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}" 
      loop: "{{ users }}"



